version: "3"

services:
  http:
    image: nginx
    volumes: 
    - "./src:/var/www/html"
    - "./deploy/nginx.default.site:/etc/nginx/conf.d/default.conf"
    ports: 
    - "80:80"
  php:
    image: kompadre/php-fpm-dev:latest
    volumes:
    - "./src:/var/www/html"
    - "./deploy/php.ini-development:/usr/local/etc/php/php.ini"
    - "./deploy/php-fpm.www.conf:/usr/local/etc/php-fpm.d/www.conf"
    ports:
    - "9000:9000" # for xdebug
    links:
      - "http:dev.local"

